### ISSUE TITLE
Error phone1.rc

### ISSUE THREAD

**Issue by Stan92** [irwansyahwii/sms-device#1]
Hi,
I'm trying to use your package with my Raspberry 
I get an error when I run your example

```
setConfigFile completed!
sendSms error: Error: Error: No such file or directory, cannot open ./phone1.rc

```
My node version is 7.7.4
I had to change the "import" line with require('sms-device').SmsDevice;

Any idea?
Thanks

**Comment by irwansyahwii** [comment]
Hi @Stan92 I checked the code, the default implementation will always create a dummy IFileManager which always return true. Can you show me your whole code?

**Comment by Stan92** [comment]
Hi,
Sure, it's very simple : 

```
     'use strict';
     let SmsDevice = require('sms-device').SmsDevice;
    let smsDevice = SmsDevice.create();
    smsDevice.setConfigFile('./phone1.rc')
        .subscribe(null, err =>{
            console.log('Error probably file not exists, error:', error);
        }, ()=>{
            console.log('setConfigFile completed!');
        });
     smsDevice.sendSms('0xxxxxxxxx', 'helooo world!')
        .subscribe(null, err =>{
            console.log('sendSms error:', err);
        }, () =>{
            console.log('sendSms completed!');
        });

```

**Comment by irwansyahwii** [comment]
@Stan92 sorry for not updating the README. So what you should do is to call setConfigFile() and pass it with your modem port e.g. /dev/usb01. So it will be like this setConfigFile('/dev/usb01')

**Comment by Stan92** [comment]
Thanks.. 
I changed it using my port (/dev/ttyUSB0)
Get another message, 

```
sendSms error: Error: Command timedout
    at SafeSubscriber.close.subscribe [as _next] (/home/pi/smstest/node_modules/raw-modem/lib/DefaultSerialPort.js:57:29)
    at SafeSubscriber.__tryOrUnsub (/home/pi/smstest/node_modules/rxjs/Subscriber.js:234:16)
    at SafeSubscriber.next (/home/pi/smstest/node_modules/rxjs/Subscriber.js:183:22)
    at Subscriber._next (/home/pi/smstest/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (/home/pi/smstest/node_modules/rxjs/Subscriber.js:89:18)
    at SerialPort.devicePort.close.err (/home/pi/smstest/node_modules/raw-modem/lib/DefaultSerialPort.js:40:27)
    at SerialPort.<anonymous> (/home/pi/smstest/node_modules/serialport/lib/serialport.js:394:30)
```
(FYI, I run my app using sudo).

Using the sendsms command from the prompt, (echo "Stan test from PI" | sudo gammu --sendsms TEXT 0xxxxxxxxx) it works.

**Comment by irwansyahwii** [comment]
@Stan92 if you want to use gammu then you have to instantiate the SmsDevice without using the factory or the SmsDevice.create() function. Pass it with a new instance of GammuModemManager() since the default factory will use WavecomModemManager

**Comment by Stan92** [comment]
Got it 
Thanks
